--- Kernel/sound/soc/codecs/Makefile
+++ Kernel/sound/soc/codecs/Makefile
@@ -42,8 +42,12 @@
 ifeq ($(CONFIG_ARIES_NTT),y)
 snd-soc-wm8994-objs := wm8994.o wm8994_s1ntt.o
 else
+ifeq ($(CONFIG_SND_VOODOO),y)
+snd-soc-wm8994-objs := wm8994.o wm8994_aries.o wm8994_voodoo.o
+else
 snd-soc-wm8994-objs := wm8994.o wm8994_aries.o
 endif
+endif
 snd-soc-wm9081-objs := wm9081.o
 snd-soc-wm9705-objs := wm9705.o
 snd-soc-wm9712-objs := wm9712.o
